//Auto generated by fragment-alias-gen.py do not edit
REGEXP Activity_all_onCreate(f) = [(
    [CB] [ENTRY] [f] void android.accounts.AccountAuthenticatorActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v7.app.ActionBarActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.ActivityGroup.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.AliasActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v7.app.AppCompatActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.ExpandableListActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.FragmentActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.LauncherActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.ListActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.TabActivity.android.app.Activity.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.Activity.android.app.Activity.onCreate(# : android.os.Bundle)
)];
REGEXP Activity_all_onResume(f) = [(
    [CB] [ENTRY] [f] void android.accounts.AccountAuthenticatorActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.ActionBarActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.app.ActivityGroup.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.app.AliasActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.AppCompatActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.app.ExpandableListActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.FragmentActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.app.LauncherActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.app.ListActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.app.TabActivity.android.app.Activity.onResume()
    |
    [CB] [ENTRY] [f] void android.app.Activity.android.app.Activity.onResume()
)];
REGEXP Activity_all_onPause(f) = [(
    [CB] [ENTRY] [f] void android.accounts.AccountAuthenticatorActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.ActionBarActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.app.ActivityGroup.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.app.AliasActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.AppCompatActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.app.ExpandableListActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.FragmentActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.app.LauncherActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.app.ListActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.app.TabActivity.android.app.Activity.onPause()
    |
    [CB] [ENTRY] [f] void android.app.Activity.android.app.Activity.onPause()
)];
REGEXP Activity_all_onStop(f) = [(
    [CB] [ENTRY] [f] void android.accounts.AccountAuthenticatorActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.ActionBarActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.app.ActivityGroup.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.app.AliasActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.AppCompatActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.app.ExpandableListActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.FragmentActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.app.LauncherActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.app.ListActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.app.TabActivity.android.app.Activity.onStop()
    |
    [CB] [ENTRY] [f] void android.app.Activity.android.app.Activity.onStop()
)];
REGEXP Activity_all_onStart(f) = [(
    [CB] [ENTRY] [f] void android.accounts.AccountAuthenticatorActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.ActionBarActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.app.ActivityGroup.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.app.AliasActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.AppCompatActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.app.ExpandableListActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.FragmentActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.app.LauncherActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.app.ListActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.app.TabActivity.android.app.Activity.onStart()
    |
    [CB] [ENTRY] [f] void android.app.Activity.android.app.Activity.onStart()
)];
REGEXP Activity_all_onDestroy(f) = [(
    [CB] [ENTRY] [f] void android.accounts.AccountAuthenticatorActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.ActionBarActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.ActivityGroup.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.AliasActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.AppCompatActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.ExpandableListActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.FragmentActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.LauncherActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.ListActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.TabActivity.android.app.Activity.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.Activity.android.app.Activity.onDestroy()
)];
REGEXP Activity_all_<init>(f) = [(
    [CB] [ENTRY] [f] void android.accounts.AccountAuthenticatorActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.ActionBarActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.app.ActivityGroup.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.app.AliasActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.AppCompatActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.app.ExpandableListActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.FragmentActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.app.LauncherActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.app.ListActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.app.TabActivity.android.app.Activity.<init>()
    |
    [CB] [ENTRY] [f] void android.app.Activity.android.app.Activity.<init>()
)];
REGEXP Activity_all_onRestart(f) = [(
    [CB] [ENTRY] [f] void android.accounts.AccountAuthenticatorActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.ActionBarActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.app.ActivityGroup.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.app.AliasActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.support.v7.app.AppCompatActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.app.ExpandableListActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.FragmentActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.app.LauncherActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.app.ListActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.app.TabActivity.android.app.Activity.onRestart()
    |
    [CB] [ENTRY] [f] void android.app.Activity.android.app.Activity.onRestart()
)]
