environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      PYSMT_SOLVER: "None"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      PYSMT_SOLVER: "None"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"
      PYSMT_SOLVER: "None"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"
      PYSMT_SOLVER: "None"


    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      PYSMT_SOLVER: "z3"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      PYSMT_SOLVER: "z3"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"
      PYSMT_SOLVER: "z3"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"
      PYSMT_SOLVER: "z3"



install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell ./ci/appveyor/install.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "%CMD_IN_ENV% pip install -r dev-requirements.txt"

  # Install the solvers
  - "%CMD_IN_ENV% python install.py --confirm-agreement"

  # Set the pythonpath
  - "python install.py --env > bindings_path.txt"
  - "SET /p BINDINGS_CMD=<bindings_path.txt"
  - "%BINDINGS_CMD%"
  - ECHO "PythonPath=%PYTHONPATH%"

build: false

test_script:
  - "%CMD_IN_ENV% python install.py --check"
  - "%CMD_IN_ENV% nosetests -v "

# after_test:
#    # If tests are successful, create a whl package for the project.
#    - "%CMD_IN_ENV% python setup.py bdist_wheel bdist_wininst"
#    - ps: "ls dist"

# artifacts:
#   # Archive the generated wheel package in the ci.appveyor.com build report.
#   - path: dist\*
