version : '3'
services:
        vvweb:
                image: fixr_verivita_web_search
                ports:
                        - "5432:5432"
                links:
                        - "db:database"
        db:
                image: 100.120.0.2:5005/fixr_verivita_tracedb
                ports:
                        - "9000:9000"
