SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] java.lang.CharSequence android.content.res.TypedArray.getText(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] java.lang.CharSequence[] android.content.res.TypedArray.getTextArray(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] android.content.res.ColorStateList android.content.res.TypedArray.getColorStateList(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] android.graphics.drawable.Drawable android.content.res.TypedArray.getDrawable(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] android.content.res.Resources android.content.res.TypedArray.getResources();
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] java.lang.String android.content.res.TypedArray.getNonConfigurationString(# : int, # : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] java.lang.String android.content.res.TypedArray.getNonResourceString(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] java.lang.String android.content.res.TypedArray.getPositionDescription();
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] java.lang.String android.content.res.TypedArray.getString(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] android.util.TypedValue android.content.res.TypedArray.peekValue(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] boolean android.content.res.TypedArray.getBoolean(# : int, # : boolean);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] boolean android.content.res.TypedArray.getValue(# : int, # : android.util.TypedValue);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] boolean android.content.res.TypedArray.hasValue(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] boolean android.content.res.TypedArray.hasValueOrEmpty(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] float android.content.res.TypedArray.getDimension(# : int , # : float);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] float android.content.res.TypedArray.getFloat(# : int, # : float);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] float android.content.res.TypedArray.getFraction(# : int, # : int, # : int, # : float);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getChangingConfigurations();
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getColor(# : int, # : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getDimensionPixelOffset(# : int, # : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getDimensionPixelSize(# : int, # : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getIndex(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getIndexCount();
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getInt(# : int, # : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getInteger(# : int , # : int );
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getLayoutDimension(# : int, # : java.lang.String);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getLayoutDimension(# : int, # : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getResourceId(# : int, # : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getThemeAttributeId(# : int, # : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.getType(# : int);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.length();
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] int android.content.res.TypedArray.extractThemeAttrs(# : int[]);
SPEC TRUE[*];[CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle() |- [CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle();


REGEXP source_of_typed_array_ad(ta) = [(ta = [CI] [EXIT] [#] android.content.res.TypedArray android.content.Context.obtainStyledAttributes(# : android.util.AttributeSet,# : int[],# : int,# : int))
    | (ta = [CI] [EXIT] [#] android.content.res.TypedArray android.content.Context.obtainStyledAttributes(# : android.util.AttributeSet,# : int[]))
    | [CB] [ENTRY] [#] java.lang.Object android.preference.Preference.onGetDefaultValue(ta : android.content.res.TypedArray, # : int)];
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] java.lang.CharSequence android.content.res.TypedArray.getText(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] java.lang.CharSequence[] android.content.res.TypedArray.getTextArray(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] android.content.res.ColorStateList android.content.res.TypedArray.getColorStateList(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] android.graphics.drawable.Drawable android.content.res.TypedArray.getDrawable(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] android.content.res.Resources android.content.res.TypedArray.getResources();
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] java.lang.String android.content.res.TypedArray.getNonConfigurationString(# : int, # : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] java.lang.String android.content.res.TypedArray.getNonResourceString(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] java.lang.String android.content.res.TypedArray.getPositionDescription();
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] java.lang.String android.content.res.TypedArray.getString(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] android.util.TypedValue android.content.res.TypedArray.peekValue(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] boolean android.content.res.TypedArray.getBoolean(# : int, # : boolean);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] boolean android.content.res.TypedArray.getValue(# : int, # : android.util.TypedValue);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] boolean android.content.res.TypedArray.hasValue(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] boolean android.content.res.TypedArray.hasValueOrEmpty(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] float android.content.res.TypedArray.getDimension(# : int , # : float);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] float android.content.res.TypedArray.getFloat(# : int, # : float);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] float android.content.res.TypedArray.getFraction(# : int, # : int, # : int, # : float);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getChangingConfigurations();
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getColor(# : int, # : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getDimensionPixelOffset(# : int, # : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getDimensionPixelSize(# : int, # : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getIndex(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getIndexCount();
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getInt(# : int, # : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getInteger(# : int , # : int );
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getLayoutDimension(# : int, # : java.lang.String);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getLayoutDimension(# : int, # : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getResourceId(# : int, # : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getThemeAttributeId(# : int, # : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.getType(# : int);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.length();
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] int android.content.res.TypedArray.extractThemeAttrs(# : int[]);
SPEC TRUE[*];source_of_typed_array_ad(ta) |+ [CI] [ENTRY] [ta] void android.content.res.TypedArray.recycle()
