
//Note: auto generated specs



//*** Enable Disable Rules ***







//Initial disable rules







SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle) ALIASES android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle) ALIASES android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onViewCreated(# : android.view.View,# : android.os.Bundle) ALIASES android.app.Fragment.onViewCreated = [android.support.v4.app.DialogFragment.onViewCreated,android.preference.PreferenceFragment.onViewCreated,android.support.v7.preference.PreferenceFragmentCompat.onViewCreated,android.support.v4.app.ListFragment.onViewCreated,android.app.ListFragment.onViewCreated,android.webkit.WebViewFragment.onViewCreated,android.app.DialogFragment.onViewCreated,android.support.v4.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onStart() ALIASES android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onResume() ALIASES android.app.Fragment.onResume = [android.support.v4.app.DialogFragment.onResume,android.preference.PreferenceFragment.onResume,android.support.v7.preference.PreferenceFragmentCompat.onResume,android.support.v4.app.ListFragment.onResume,android.app.ListFragment.onResume,android.webkit.WebViewFragment.onResume,android.app.DialogFragment.onResume,android.support.v4.app.Fragment.onResume,android.app.Fragment.onResume];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onPause() ALIASES android.app.Fragment.onPause = [android.support.v4.app.DialogFragment.onPause,android.preference.PreferenceFragment.onPause,android.support.v7.preference.PreferenceFragmentCompat.onPause,android.support.v4.app.ListFragment.onPause,android.app.ListFragment.onPause,android.webkit.WebViewFragment.onPause,android.app.DialogFragment.onPause,android.support.v4.app.Fragment.onPause,android.app.Fragment.onPause];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle) ALIASES android.app.Fragment.onSaveInstanceState = [android.support.v4.app.DialogFragment.onSaveInstanceState,android.preference.PreferenceFragment.onSaveInstanceState,android.support.v7.preference.PreferenceFragmentCompat.onSaveInstanceState,android.support.v4.app.ListFragment.onSaveInstanceState,android.app.ListFragment.onSaveInstanceState,android.webkit.WebViewFragment.onSaveInstanceState,android.app.DialogFragment.onSaveInstanceState,android.support.v4.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onStop() ALIASES android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView() ALIASES android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onDestroy() ALIASES android.app.Fragment.onDestroy = [android.support.v4.app.DialogFragment.onDestroy,android.preference.PreferenceFragment.onDestroy,android.support.v7.preference.PreferenceFragmentCompat.onDestroy,android.support.v4.app.ListFragment.onDestroy,android.app.ListFragment.onDestroy,android.webkit.WebViewFragment.onDestroy,android.app.DialogFragment.onDestroy,android.support.v4.app.Fragment.onDestroy,android.app.Fragment.onDestroy];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onDetach() ALIASES android.app.Fragment.onDetach = [android.support.v4.app.DialogFragment.onDetach,android.preference.PreferenceFragment.onDetach,android.support.v7.preference.PreferenceFragmentCompat.onDetach,android.support.v4.app.ListFragment.onDetach,android.app.ListFragment.onDetach,android.webkit.WebViewFragment.onDetach,android.app.DialogFragment.onDetach,android.support.v4.app.Fragment.onDetach,android.app.Fragment.onDetach];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [f] void android.app.Fragment.onActivityCreated(# : android.os.Bundle) ALIASES android.app.Fragment.onActivityCreated = [android.support.v4.app.DialogFragment.onActivityCreated,android.preference.PreferenceFragment.onActivityCreated,android.support.v7.preference.PreferenceFragmentCompat.onActivityCreated,android.support.v4.app.ListFragment.onActivityCreated,android.app.ListFragment.onActivityCreated,android.webkit.WebViewFragment.onActivityCreated,android.app.DialogFragment.onActivityCreated,android.support.v4.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated];


//Initialization

//Lifecycle

SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onAttach(# : android.app.Activity)) |- [CB] [ENTRY] [f] void android.app.Fragment.onAttach(# : android.app.Activity) ALIASES android.app.Fragment.onAttach = [android.support.v4.app.DialogFragment.onAttach,android.preference.PreferenceFragment.onAttach,android.support.v7.preference.PreferenceFragmentCompat.onAttach,android.support.v4.app.ListFragment.onAttach,android.app.ListFragment.onAttach,android.webkit.WebViewFragment.onAttach,android.app.DialogFragment.onAttach,android.support.v4.app.Fragment.onAttach,android.app.Fragment.onAttach];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onAttach(# : android.app.Activity)) |+ [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle) ALIASES android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate],android.app.Fragment.onAttach = [android.support.v4.app.DialogFragment.onAttach,android.preference.PreferenceFragment.onAttach,android.support.v7.preference.PreferenceFragmentCompat.onAttach,android.support.v4.app.ListFragment.onAttach,android.app.ListFragment.onAttach,android.webkit.WebViewFragment.onAttach,android.app.DialogFragment.onAttach,android.support.v4.app.Fragment.onAttach,android.app.Fragment.onAttach,android.app.Fragment.onAttach];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle)) |- [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle) ALIASES android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle)) |+ [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle) ALIASES android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate],android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)) |- [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle) ALIASES android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)) |+ [CB] [ENTRY] [f] void android.app.Fragment.onViewCreated(# : android.view.View,# : android.os.Bundle) ALIASES android.app.Fragment.onViewCreated = [android.support.v4.app.DialogFragment.onViewCreated,android.preference.PreferenceFragment.onViewCreated,android.support.v7.preference.PreferenceFragmentCompat.onViewCreated,android.support.v4.app.ListFragment.onViewCreated,android.app.ListFragment.onViewCreated,android.webkit.WebViewFragment.onViewCreated,android.app.DialogFragment.onViewCreated,android.support.v4.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated],android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onViewCreated(# : android.view.View,# : android.os.Bundle)) |- [CB] [ENTRY] [f] void android.app.Fragment.onViewCreated(# : android.view.View,# : android.os.Bundle) ALIASES android.app.Fragment.onViewCreated = [android.support.v4.app.DialogFragment.onViewCreated,android.preference.PreferenceFragment.onViewCreated,android.support.v7.preference.PreferenceFragmentCompat.onViewCreated,android.support.v4.app.ListFragment.onViewCreated,android.app.ListFragment.onViewCreated,android.webkit.WebViewFragment.onViewCreated,android.app.DialogFragment.onViewCreated,android.support.v4.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated];


//TODO: onActivityCreated and onViewStateRestored conditional on init, for now left unspecified

//When added in the below rule will also need to know whether its in the starting cycle.

SPEC (((TRUE)[*]); [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)) |+ [CB] [ENTRY] [f] void android.app.Fragment.onActivityCreated(# : android.os.Bundle) ALIASES android.app.Fragment.onActivityCreated = [android.support.v4.app.DialogFragment.onActivityCreated,android.preference.PreferenceFragment.onActivityCreated,android.support.v7.preference.PreferenceFragmentCompat.onActivityCreated,android.support.v4.app.ListFragment.onActivityCreated,android.app.ListFragment.onActivityCreated,android.webkit.WebViewFragment.onActivityCreated,android.app.DialogFragment.onActivityCreated,android.support.v4.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated],android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onActivityCreated(# : android.os.Bundle)) |- [CB] [ENTRY] [f] void android.app.Fragment.onActivityCreated(# : android.os.Bundle) ALIASES android.app.Fragment.onActivityCreated = [android.support.v4.app.DialogFragment.onActivityCreated,android.preference.PreferenceFragment.onActivityCreated,android.support.v7.preference.PreferenceFragmentCompat.onActivityCreated,android.support.v4.app.ListFragment.onActivityCreated,android.app.ListFragment.onActivityCreated,android.webkit.WebViewFragment.onActivityCreated,android.app.DialogFragment.onActivityCreated,android.support.v4.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStart()) |- [CB] [ENTRY] [f] void android.app.Fragment.onActivityCreated(# : android.os.Bundle) ALIASES android.app.Fragment.onActivityCreated = [android.support.v4.app.DialogFragment.onActivityCreated,android.preference.PreferenceFragment.onActivityCreated,android.support.v7.preference.PreferenceFragmentCompat.onActivityCreated,android.support.v4.app.ListFragment.onActivityCreated,android.app.ListFragment.onActivityCreated,android.webkit.WebViewFragment.onActivityCreated,android.app.DialogFragment.onActivityCreated,android.support.v4.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated],android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart];


//following rule was commented out, we are overaproximating onViewCreated as it depends on the return value of onCreateView sometimes, this can be modeled precisely but not needed yet

//SPEC TRUE[*]; [CB] [ENTRY] [f] void android.app.Fragment.onViewCreated(# : android.view.View,# : android.os.Bundle) |+ [CB] [ENTRY] [f] void android.app.Fragment.onStart();



SPEC (((TRUE)[*]); [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)) |+ [CB] [ENTRY] [f] void android.app.Fragment.onStart() ALIASES android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView],android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStart()) |- [CB] [ENTRY] [f] void android.app.Fragment.onViewCreated(# : android.view.View,# : android.os.Bundle) ALIASES android.app.Fragment.onViewCreated = [android.support.v4.app.DialogFragment.onViewCreated,android.preference.PreferenceFragment.onViewCreated,android.support.v7.preference.PreferenceFragmentCompat.onViewCreated,android.support.v4.app.ListFragment.onViewCreated,android.app.ListFragment.onViewCreated,android.webkit.WebViewFragment.onViewCreated,android.app.DialogFragment.onViewCreated,android.support.v4.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated,android.app.Fragment.onViewCreated],android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart];


SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStart()) |- [CB] [ENTRY] [f] void android.app.Fragment.onStart() ALIASES android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStart()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onResume() ALIASES android.app.Fragment.onResume = [android.support.v4.app.DialogFragment.onResume,android.preference.PreferenceFragment.onResume,android.support.v7.preference.PreferenceFragmentCompat.onResume,android.support.v4.app.ListFragment.onResume,android.app.ListFragment.onResume,android.webkit.WebViewFragment.onResume,android.app.DialogFragment.onResume,android.support.v4.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume],android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onResume()) |- [CB] [ENTRY] [f] void android.app.Fragment.onResume() ALIASES android.app.Fragment.onResume = [android.support.v4.app.DialogFragment.onResume,android.preference.PreferenceFragment.onResume,android.support.v7.preference.PreferenceFragmentCompat.onResume,android.support.v4.app.ListFragment.onResume,android.app.ListFragment.onResume,android.webkit.WebViewFragment.onResume,android.app.DialogFragment.onResume,android.support.v4.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onResume()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onPause() ALIASES android.app.Fragment.onResume = [android.support.v4.app.DialogFragment.onResume,android.preference.PreferenceFragment.onResume,android.support.v7.preference.PreferenceFragmentCompat.onResume,android.support.v4.app.ListFragment.onResume,android.app.ListFragment.onResume,android.webkit.WebViewFragment.onResume,android.app.DialogFragment.onResume,android.support.v4.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume],android.app.Fragment.onPause = [android.support.v4.app.DialogFragment.onPause,android.preference.PreferenceFragment.onPause,android.support.v7.preference.PreferenceFragmentCompat.onPause,android.support.v4.app.ListFragment.onPause,android.app.ListFragment.onPause,android.webkit.WebViewFragment.onPause,android.app.DialogFragment.onPause,android.support.v4.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onPause()) |- [CB] [ENTRY] [f] void android.app.Fragment.onPause() ALIASES android.app.Fragment.onPause = [android.support.v4.app.DialogFragment.onPause,android.preference.PreferenceFragment.onPause,android.support.v7.preference.PreferenceFragmentCompat.onPause,android.support.v4.app.ListFragment.onPause,android.app.ListFragment.onPause,android.webkit.WebViewFragment.onPause,android.app.DialogFragment.onPause,android.support.v4.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause];


SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStart()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle) ALIASES android.app.Fragment.onSaveInstanceState = [android.support.v4.app.DialogFragment.onSaveInstanceState,android.preference.PreferenceFragment.onSaveInstanceState,android.support.v7.preference.PreferenceFragmentCompat.onSaveInstanceState,android.support.v4.app.ListFragment.onSaveInstanceState,android.app.ListFragment.onSaveInstanceState,android.webkit.WebViewFragment.onSaveInstanceState,android.app.DialogFragment.onSaveInstanceState,android.support.v4.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState],android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart];


SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onResume()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle) ALIASES android.app.Fragment.onSaveInstanceState = [android.support.v4.app.DialogFragment.onSaveInstanceState,android.preference.PreferenceFragment.onSaveInstanceState,android.support.v7.preference.PreferenceFragmentCompat.onSaveInstanceState,android.support.v4.app.ListFragment.onSaveInstanceState,android.app.ListFragment.onSaveInstanceState,android.webkit.WebViewFragment.onSaveInstanceState,android.app.DialogFragment.onSaveInstanceState,android.support.v4.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState],android.app.Fragment.onResume = [android.support.v4.app.DialogFragment.onResume,android.preference.PreferenceFragment.onResume,android.support.v7.preference.PreferenceFragmentCompat.onResume,android.support.v4.app.ListFragment.onResume,android.app.ListFragment.onResume,android.webkit.WebViewFragment.onResume,android.app.DialogFragment.onResume,android.support.v4.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume];


SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onPause()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onStop() ALIASES android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop],android.app.Fragment.onPause = [android.support.v4.app.DialogFragment.onPause,android.preference.PreferenceFragment.onPause,android.support.v7.preference.PreferenceFragmentCompat.onPause,android.support.v4.app.ListFragment.onPause,android.app.ListFragment.onPause,android.webkit.WebViewFragment.onPause,android.app.DialogFragment.onPause,android.support.v4.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onPause()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onResume() ALIASES android.app.Fragment.onResume = [android.support.v4.app.DialogFragment.onResume,android.preference.PreferenceFragment.onResume,android.support.v7.preference.PreferenceFragmentCompat.onResume,android.support.v4.app.ListFragment.onResume,android.app.ListFragment.onResume,android.webkit.WebViewFragment.onResume,android.app.DialogFragment.onResume,android.support.v4.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume],android.app.Fragment.onPause = [android.support.v4.app.DialogFragment.onPause,android.preference.PreferenceFragment.onPause,android.support.v7.preference.PreferenceFragmentCompat.onPause,android.support.v4.app.ListFragment.onPause,android.app.ListFragment.onPause,android.webkit.WebViewFragment.onPause,android.app.DialogFragment.onPause,android.support.v4.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause];




//Removed because onSaveInstanceState "can happenany time before onDestroy" according to expanded fragment lifecycle.  I am going to stick with onResume enabling it until I see otherwise



//SPEC ((TRUE)[*]); ([CB] [ENTRY] [f] void android.app.Fragment.onResume()) |- [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle);



//SPEC ((TRUE)[*]); ([CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle)) |- [CB] [ENTRY] [f] void android.app.Fragment.onResume();



//SPEC TRUE[*]; [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle) |+ [CB] [ENTRY] [f] void android.app.Fragment.onStop();







SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle)) |- [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle) ALIASES android.app.Fragment.onSaveInstanceState = [android.support.v4.app.DialogFragment.onSaveInstanceState,android.preference.PreferenceFragment.onSaveInstanceState,android.support.v7.preference.PreferenceFragmentCompat.onSaveInstanceState,android.support.v4.app.ListFragment.onSaveInstanceState,android.app.ListFragment.onSaveInstanceState,android.webkit.WebViewFragment.onSaveInstanceState,android.app.DialogFragment.onSaveInstanceState,android.support.v4.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStop()) |- [CB] [ENTRY] [f] void android.app.Fragment.onStop() ALIASES android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop];








//onStop branching control flow







SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStop()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onStart() ALIASES android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart],android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStop()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle) ALIASES android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate],android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStop()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView() ALIASES android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView],android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop];








SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStart()) |- [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView() ALIASES android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView],android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStart()) |- [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle) ALIASES android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart],android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView()) |- [CB] [ENTRY] [f] void android.app.Fragment.onStart() ALIASES android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart],android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView()) |- [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle) ALIASES android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate],android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle)) |- [CB] [ENTRY] [f] void android.app.Fragment.onStart() ALIASES android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart],android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle)) |- [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView() ALIASES android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView],android.app.Fragment.onCreate = [android.support.v4.app.DialogFragment.onCreate,android.preference.PreferenceFragment.onCreate,android.support.v7.preference.PreferenceFragmentCompat.onCreate,android.support.v4.app.ListFragment.onCreate,android.app.ListFragment.onCreate,android.webkit.WebViewFragment.onCreate,android.app.DialogFragment.onCreate,android.support.v4.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate,android.app.Fragment.onCreate];


//onDstroyView branching control



SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView()) |- [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView() ALIASES android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onDestroy() ALIASES android.app.Fragment.onDestroy = [android.support.v4.app.DialogFragment.onDestroy,android.preference.PreferenceFragment.onDestroy,android.support.v7.preference.PreferenceFragmentCompat.onDestroy,android.support.v4.app.ListFragment.onDestroy,android.app.ListFragment.onDestroy,android.webkit.WebViewFragment.onDestroy,android.app.DialogFragment.onDestroy,android.support.v4.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy],android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView()) |+ [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle) ALIASES android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView],android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView];


SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDestroy()) |- [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle) ALIASES android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView],android.app.Fragment.onDestroy = [android.support.v4.app.DialogFragment.onDestroy,android.preference.PreferenceFragment.onDestroy,android.support.v7.preference.PreferenceFragmentCompat.onDestroy,android.support.v4.app.ListFragment.onDestroy,android.app.ListFragment.onDestroy,android.webkit.WebViewFragment.onDestroy,android.app.DialogFragment.onDestroy,android.support.v4.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)) |- [CB] [ENTRY] [f] void android.app.Fragment.onDestroy() ALIASES android.app.Fragment.onCreateView = [android.support.v4.app.DialogFragment.onCreateView,android.preference.PreferenceFragment.onCreateView,android.support.v7.preference.PreferenceFragmentCompat.onCreateView,android.support.v4.app.ListFragment.onCreateView,android.app.ListFragment.onCreateView,android.webkit.WebViewFragment.onCreateView,android.app.DialogFragment.onCreateView,android.support.v4.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView,android.app.Fragment.onCreateView],android.app.Fragment.onDestroy = [android.support.v4.app.DialogFragment.onDestroy,android.preference.PreferenceFragment.onDestroy,android.support.v7.preference.PreferenceFragmentCompat.onDestroy,android.support.v4.app.ListFragment.onDestroy,android.app.ListFragment.onDestroy,android.webkit.WebViewFragment.onDestroy,android.app.DialogFragment.onDestroy,android.support.v4.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy];


SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDestroy()) |- [CB] [ENTRY] [f] void android.app.Fragment.onDestroy() ALIASES android.app.Fragment.onDestroy = [android.support.v4.app.DialogFragment.onDestroy,android.preference.PreferenceFragment.onDestroy,android.support.v7.preference.PreferenceFragmentCompat.onDestroy,android.support.v4.app.ListFragment.onDestroy,android.app.ListFragment.onDestroy,android.webkit.WebViewFragment.onDestroy,android.app.DialogFragment.onDestroy,android.support.v4.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDestroy()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onDetach() ALIASES android.app.Fragment.onDetach = [android.support.v4.app.DialogFragment.onDetach,android.preference.PreferenceFragment.onDetach,android.support.v7.preference.PreferenceFragmentCompat.onDetach,android.support.v4.app.ListFragment.onDetach,android.app.ListFragment.onDetach,android.webkit.WebViewFragment.onDetach,android.app.DialogFragment.onDetach,android.support.v4.app.Fragment.onDetach,android.app.Fragment.onDetach,android.app.Fragment.onDetach],android.app.Fragment.onDestroy = [android.support.v4.app.DialogFragment.onDestroy,android.preference.PreferenceFragment.onDestroy,android.support.v7.preference.PreferenceFragmentCompat.onDestroy,android.support.v4.app.ListFragment.onDestroy,android.app.ListFragment.onDestroy,android.webkit.WebViewFragment.onDestroy,android.app.DialogFragment.onDestroy,android.support.v4.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy,android.app.Fragment.onDestroy];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDetach()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onAttach(# : android.app.Activity) ALIASES android.app.Fragment.onDetach = [android.support.v4.app.DialogFragment.onDetach,android.preference.PreferenceFragment.onDetach,android.support.v7.preference.PreferenceFragmentCompat.onDetach,android.support.v4.app.ListFragment.onDetach,android.app.ListFragment.onDetach,android.webkit.WebViewFragment.onDetach,android.app.DialogFragment.onDetach,android.support.v4.app.Fragment.onDetach,android.app.Fragment.onDetach,android.app.Fragment.onDetach,android.app.Fragment.onDetach],android.app.Fragment.onAttach = [android.support.v4.app.DialogFragment.onAttach,android.preference.PreferenceFragment.onAttach,android.support.v7.preference.PreferenceFragmentCompat.onAttach,android.support.v4.app.ListFragment.onAttach,android.app.ListFragment.onAttach,android.webkit.WebViewFragment.onAttach,android.app.DialogFragment.onAttach,android.support.v4.app.Fragment.onAttach,android.app.Fragment.onAttach,android.app.Fragment.onAttach,android.app.Fragment.onAttach];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onDetach()) |- [CB] [ENTRY] [f] void android.app.Fragment.onDetach() ALIASES android.app.Fragment.onDetach = [android.support.v4.app.DialogFragment.onDetach,android.preference.PreferenceFragment.onDetach,android.support.v7.preference.PreferenceFragmentCompat.onDetach,android.support.v4.app.ListFragment.onDetach,android.app.ListFragment.onDetach,android.webkit.WebViewFragment.onDetach,android.app.DialogFragment.onDetach,android.support.v4.app.Fragment.onDetach,android.app.Fragment.onDetach,android.app.Fragment.onDetach,android.app.Fragment.onDetach,android.app.Fragment.onDetach];


//parent activity finish can trigger the following edges:

SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onActivityCreated(# : android.os.Bundle)) |+ [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView() ALIASES android.app.Fragment.onDestroyView = [android.support.v4.app.DialogFragment.onDestroyView,android.preference.PreferenceFragment.onDestroyView,android.support.v7.preference.PreferenceFragmentCompat.onDestroyView,android.support.v4.app.ListFragment.onDestroyView,android.app.ListFragment.onDestroyView,android.webkit.WebViewFragment.onDestroyView,android.app.DialogFragment.onDestroyView,android.support.v4.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView,android.app.Fragment.onDestroyView],android.app.Fragment.onActivityCreated = [android.support.v4.app.DialogFragment.onActivityCreated,android.preference.PreferenceFragment.onActivityCreated,android.support.v7.preference.PreferenceFragmentCompat.onActivityCreated,android.support.v4.app.ListFragment.onActivityCreated,android.app.ListFragment.onActivityCreated,android.webkit.WebViewFragment.onActivityCreated,android.app.DialogFragment.onActivityCreated,android.support.v4.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated,android.app.Fragment.onActivityCreated];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStart()) |+ [CB] [ENTRY] [f] void android.app.Fragment.onStop() ALIASES android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop],android.app.Fragment.onStart = [android.support.v4.app.DialogFragment.onStart,android.preference.PreferenceFragment.onStart,android.support.v7.preference.PreferenceFragmentCompat.onStart,android.support.v4.app.ListFragment.onStart,android.app.ListFragment.onStart,android.webkit.WebViewFragment.onStart,android.app.DialogFragment.onStart,android.support.v4.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart,android.app.Fragment.onStart];
SPEC [CB] [ENTRY] [f] void android.app.Fragment.onStop() |- [CB] [ENTRY] [f] void android.app.Fragment.onResume() ALIASES android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop],android.app.Fragment.onResume = [android.support.v4.app.DialogFragment.onResume,android.preference.PreferenceFragment.onResume,android.support.v7.preference.PreferenceFragmentCompat.onResume,android.support.v4.app.ListFragment.onResume,android.app.ListFragment.onResume,android.webkit.WebViewFragment.onResume,android.app.DialogFragment.onResume,android.support.v4.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume,android.app.Fragment.onResume];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStop()) |- [CB] [ENTRY] [f] void android.app.Fragment.onPause() ALIASES android.app.Fragment.onPause = [android.support.v4.app.DialogFragment.onPause,android.preference.PreferenceFragment.onPause,android.support.v7.preference.PreferenceFragmentCompat.onPause,android.support.v4.app.ListFragment.onPause,android.app.ListFragment.onPause,android.webkit.WebViewFragment.onPause,android.app.DialogFragment.onPause,android.support.v4.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause,android.app.Fragment.onPause],android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [f] void android.app.Fragment.onStop()) |- [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle) ALIASES android.app.Fragment.onSaveInstanceState = [android.support.v4.app.DialogFragment.onSaveInstanceState,android.preference.PreferenceFragment.onSaveInstanceState,android.support.v7.preference.PreferenceFragmentCompat.onSaveInstanceState,android.support.v4.app.ListFragment.onSaveInstanceState,android.app.ListFragment.onSaveInstanceState,android.webkit.WebViewFragment.onSaveInstanceState,android.app.DialogFragment.onSaveInstanceState,android.support.v4.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState,android.app.Fragment.onSaveInstanceState],android.app.Fragment.onStop = [android.support.v4.app.DialogFragment.onStop,android.preference.PreferenceFragment.onStop,android.support.v7.preference.PreferenceFragmentCompat.onStop,android.support.v4.app.ListFragment.onStop,android.app.ListFragment.onStop,android.webkit.WebViewFragment.onStop,android.app.DialogFragment.onStop,android.support.v4.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop,android.app.Fragment.onStop];
