
//Initial disables:

SPEC ((FALSE)[*]) |- [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) ALIASES android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [a] void android.app.Activity.onResume() ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [a] void android.app.Activity.onPause() ALIASES android.app.Activity.onPause = [android.app.LauncherActivity.onPause,android.support.v7.app.AppCompatActivity.onPause,android.app.ExpandableListActivity.onPause,android.app.ListActivity.onPause,android.app.AliasActivity.onPause,android.accounts.AccountAuthenticatorActivity.onPause,android.preference.PreferenceActivity.onPause,android.support.v4.app.FragmentActivity.onPause,android.app.TabActivity.onPause,android.support.v7.app.ActionBarActivity.onPause,android.app.ActivityGroup.onPause,android.app.Activity.onPause];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [a] void android.app.Activity.onStop() ALIASES android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [a] void android.app.Activity.onDestroy() ALIASES android.app.Activity.onDestroy = [android.app.LauncherActivity.onDestroy,android.support.v7.app.AppCompatActivity.onDestroy,android.app.ExpandableListActivity.onDestroy,android.app.ListActivity.onDestroy,android.app.AliasActivity.onDestroy,android.accounts.AccountAuthenticatorActivity.onDestroy,android.preference.PreferenceActivity.onDestroy,android.support.v4.app.FragmentActivity.onDestroy,android.app.TabActivity.onDestroy,android.support.v7.app.ActionBarActivity.onDestroy,android.app.ActivityGroup.onDestroy,android.app.Activity.onDestroy];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [a] void android.app.Activity.onStart() ALIASES android.app.Activity.onStart = [android.app.LauncherActivity.onStart,android.support.v7.app.AppCompatActivity.onStart,android.app.ExpandableListActivity.onStart,android.app.ListActivity.onStart,android.app.AliasActivity.onStart,android.accounts.AccountAuthenticatorActivity.onStart,android.preference.PreferenceActivity.onStart,android.support.v4.app.FragmentActivity.onStart,android.app.TabActivity.onStart,android.support.v7.app.ActionBarActivity.onStart,android.app.ActivityGroup.onStart,android.app.Activity.onStart];
SPEC ((FALSE)[*]) |- [CB] [ENTRY] [a] void android.app.Activity.onRestart() ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart];




//create start and resume chain

SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.<init>()) |+ [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) ALIASES android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate],android.app.Activity.<init> = [android.app.LauncherActivity.<init>,android.support.v7.app.AppCompatActivity.<init>,android.app.ExpandableListActivity.<init>,android.app.ListActivity.<init>,android.app.AliasActivity.<init>,android.accounts.AccountAuthenticatorActivity.<init>,android.preference.PreferenceActivity.<init>,android.support.v4.app.FragmentActivity.<init>,android.app.TabActivity.<init>,android.support.v7.app.ActionBarActivity.<init>,android.app.ActivityGroup.<init>,android.app.Activity.<init>];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.<init>()) |- [CB] [ENTRY] [a] void android.app.Activity.<init>() ALIASES android.app.Activity.<init> = [android.app.LauncherActivity.<init>,android.support.v7.app.AppCompatActivity.<init>,android.app.ExpandableListActivity.<init>,android.app.ListActivity.<init>,android.app.AliasActivity.<init>,android.accounts.AccountAuthenticatorActivity.<init>,android.preference.PreferenceActivity.<init>,android.support.v4.app.FragmentActivity.<init>,android.app.TabActivity.<init>,android.support.v7.app.ActionBarActivity.<init>,android.app.ActivityGroup.<init>,android.app.Activity.<init>,android.app.Activity.<init>];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle)) |- [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) ALIASES android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle)) |+ [CB] [ENTRY] [a] void android.app.Activity.onStart() ALIASES android.app.Activity.onStart = [android.app.LauncherActivity.onStart,android.support.v7.app.AppCompatActivity.onStart,android.app.ExpandableListActivity.onStart,android.app.ListActivity.onStart,android.app.AliasActivity.onStart,android.accounts.AccountAuthenticatorActivity.onStart,android.preference.PreferenceActivity.onStart,android.support.v4.app.FragmentActivity.onStart,android.app.TabActivity.onStart,android.support.v7.app.ActionBarActivity.onStart,android.app.ActivityGroup.onStart,android.app.Activity.onStart,android.app.Activity.onStart],android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate];
//onCreate can go directly to onStop if a "finish" method is called, in lifecycle we need to overapproximate this behavior

SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle)) |+ [CB] [ENTRY] [a] void android.app.Activity.onStop() ALIASES android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate],android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onStart()) |+ [CB] [ENTRY] [a] void android.app.Activity.onStop() ALIASES android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop],android.app.Activity.onStart = [android.app.LauncherActivity.onStart,android.support.v7.app.AppCompatActivity.onStart,android.app.ExpandableListActivity.onStart,android.app.ListActivity.onStart,android.app.AliasActivity.onStart,android.accounts.AccountAuthenticatorActivity.onStart,android.preference.PreferenceActivity.onStart,android.support.v4.app.FragmentActivity.onStart,android.app.TabActivity.onStart,android.support.v7.app.ActionBarActivity.onStart,android.app.ActivityGroup.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart];


SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onStart()) |- [CB] [ENTRY] [a] void android.app.Activity.onStart() ALIASES android.app.Activity.onStart = [android.app.LauncherActivity.onStart,android.support.v7.app.AppCompatActivity.onStart,android.app.ExpandableListActivity.onStart,android.app.ListActivity.onStart,android.app.AliasActivity.onStart,android.accounts.AccountAuthenticatorActivity.onStart,android.preference.PreferenceActivity.onStart,android.support.v4.app.FragmentActivity.onStart,android.app.TabActivity.onStart,android.support.v7.app.ActionBarActivity.onStart,android.app.ActivityGroup.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onStart()) |+ [CB] [ENTRY] [a] void android.app.Activity.onResume() ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume],android.app.Activity.onStart = [android.app.LauncherActivity.onStart,android.support.v7.app.AppCompatActivity.onStart,android.app.ExpandableListActivity.onStart,android.app.ListActivity.onStart,android.app.AliasActivity.onStart,android.accounts.AccountAuthenticatorActivity.onStart,android.preference.PreferenceActivity.onStart,android.support.v4.app.FragmentActivity.onStart,android.app.TabActivity.onStart,android.support.v7.app.ActionBarActivity.onStart,android.app.ActivityGroup.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onResume()) |- [CB] [ENTRY] [a] void android.app.Activity.onResume() ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onResume()) |+ [CB] [ENTRY] [a] void android.app.Activity.onPause() ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume],android.app.Activity.onPause = [android.app.LauncherActivity.onPause,android.support.v7.app.AppCompatActivity.onPause,android.app.ExpandableListActivity.onPause,android.app.ListActivity.onPause,android.app.AliasActivity.onPause,android.accounts.AccountAuthenticatorActivity.onPause,android.preference.PreferenceActivity.onPause,android.support.v4.app.FragmentActivity.onPause,android.app.TabActivity.onPause,android.support.v7.app.ActionBarActivity.onPause,android.app.ActivityGroup.onPause,android.app.Activity.onPause,android.app.Activity.onPause];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onPause()) |- [CB] [ENTRY] [a] void android.app.Activity.onPause() ALIASES android.app.Activity.onPause = [android.app.LauncherActivity.onPause,android.support.v7.app.AppCompatActivity.onPause,android.app.ExpandableListActivity.onPause,android.app.ListActivity.onPause,android.app.AliasActivity.onPause,android.accounts.AccountAuthenticatorActivity.onPause,android.preference.PreferenceActivity.onPause,android.support.v4.app.FragmentActivity.onPause,android.app.TabActivity.onPause,android.support.v7.app.ActionBarActivity.onPause,android.app.ActivityGroup.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause];


//Stop branch from pause

SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onPause()) |+ [CB] [ENTRY] [a] void android.app.Activity.onStop() ALIASES android.app.Activity.onPause = [android.app.LauncherActivity.onPause,android.support.v7.app.AppCompatActivity.onPause,android.app.ExpandableListActivity.onPause,android.app.ListActivity.onPause,android.app.AliasActivity.onPause,android.accounts.AccountAuthenticatorActivity.onPause,android.preference.PreferenceActivity.onPause,android.support.v4.app.FragmentActivity.onPause,android.app.TabActivity.onPause,android.support.v7.app.ActionBarActivity.onPause,android.app.ActivityGroup.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause],android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onStop()) |- [CB] [ENTRY] [a] void android.app.Activity.onStop() ALIASES android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onResume()) |- [CB] [ENTRY] [a] void android.app.Activity.onStop() ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume],android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onStop()) |- [CB] [ENTRY] [a] void android.app.Activity.onResume() ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume],android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop];


SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onStop()) |+ [CB] [ENTRY] [a] void android.app.Activity.onRestart() ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart],android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop];
//Resume branch from pause



SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onPause()) |+ [CB] [ENTRY] [a] void android.app.Activity.onResume() ALIASES android.app.Activity.onPause = [android.app.LauncherActivity.onPause,android.support.v7.app.AppCompatActivity.onPause,android.app.ExpandableListActivity.onPause,android.app.ListActivity.onPause,android.app.AliasActivity.onPause,android.accounts.AccountAuthenticatorActivity.onPause,android.preference.PreferenceActivity.onPause,android.support.v4.app.FragmentActivity.onPause,android.app.TabActivity.onPause,android.support.v7.app.ActionBarActivity.onPause,android.app.ActivityGroup.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause],android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onResume()) |- [CB] [ENTRY] [a] void android.app.Activity.onStop() ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume],android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onResume()) |- [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume],android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate];


//Create branch from pause

SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onPause()) |+ [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) ALIASES android.app.Activity.onPause = [android.app.LauncherActivity.onPause,android.support.v7.app.AppCompatActivity.onPause,android.app.ExpandableListActivity.onPause,android.app.ListActivity.onPause,android.app.AliasActivity.onPause,android.accounts.AccountAuthenticatorActivity.onPause,android.preference.PreferenceActivity.onPause,android.support.v4.app.FragmentActivity.onPause,android.app.TabActivity.onPause,android.support.v7.app.ActionBarActivity.onPause,android.app.ActivityGroup.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause,android.app.Activity.onPause],android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle)) |- [CB] [ENTRY] [a] void android.app.Activity.onRestart() ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart],android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle)) |- [CB] [ENTRY] [a] void android.app.Activity.onResume() ALIASES android.app.Activity.onResume = [android.app.LauncherActivity.onResume,android.support.v7.app.AppCompatActivity.onResume,android.app.ExpandableListActivity.onResume,android.app.ListActivity.onResume,android.app.AliasActivity.onResume,android.accounts.AccountAuthenticatorActivity.onResume,android.preference.PreferenceActivity.onResume,android.support.v4.app.FragmentActivity.onResume,android.app.TabActivity.onResume,android.support.v7.app.ActionBarActivity.onResume,android.app.ActivityGroup.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume,android.app.Activity.onResume],android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate];
//SPEC TRUE[*];[CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) |- [CB] [ENTRY] [a] void android.app.Activity.onStop();





//Restart branch from stop

SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onStop()) |+ [CB] [ENTRY] [a] void android.app.Activity.onRestart() ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart],android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onRestart()) |+ [CB] [ENTRY] [a] void android.app.Activity.onStart() ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart],android.app.Activity.onStart = [android.app.LauncherActivity.onStart,android.support.v7.app.AppCompatActivity.onStart,android.app.ExpandableListActivity.onStart,android.app.ListActivity.onStart,android.app.AliasActivity.onStart,android.accounts.AccountAuthenticatorActivity.onStart,android.preference.PreferenceActivity.onStart,android.support.v4.app.FragmentActivity.onStart,android.app.TabActivity.onStart,android.support.v7.app.ActionBarActivity.onStart,android.app.ActivityGroup.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart,android.app.Activity.onStart];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onRestart()) |- [CB] [ENTRY] [a] void android.app.Activity.onDestroy() ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart],android.app.Activity.onDestroy = [android.app.LauncherActivity.onDestroy,android.support.v7.app.AppCompatActivity.onDestroy,android.app.ExpandableListActivity.onDestroy,android.app.ListActivity.onDestroy,android.app.AliasActivity.onDestroy,android.accounts.AccountAuthenticatorActivity.onDestroy,android.preference.PreferenceActivity.onDestroy,android.support.v4.app.FragmentActivity.onDestroy,android.app.TabActivity.onDestroy,android.support.v7.app.ActionBarActivity.onDestroy,android.app.ActivityGroup.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onRestart()) |- [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart],android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onRestart()) |- [CB] [ENTRY] [a] void android.app.Activity.onRestart() ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart];


//Destroy branch from stop

SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onStop()) |+ [CB] [ENTRY] [a] void android.app.Activity.onDestroy() ALIASES android.app.Activity.onStop = [android.app.LauncherActivity.onStop,android.support.v7.app.AppCompatActivity.onStop,android.app.ExpandableListActivity.onStop,android.app.ListActivity.onStop,android.app.AliasActivity.onStop,android.accounts.AccountAuthenticatorActivity.onStop,android.preference.PreferenceActivity.onStop,android.support.v4.app.FragmentActivity.onStop,android.app.TabActivity.onStop,android.support.v7.app.ActionBarActivity.onStop,android.app.ActivityGroup.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop,android.app.Activity.onStop],android.app.Activity.onDestroy = [android.app.LauncherActivity.onDestroy,android.support.v7.app.AppCompatActivity.onDestroy,android.app.ExpandableListActivity.onDestroy,android.app.ListActivity.onDestroy,android.app.AliasActivity.onDestroy,android.accounts.AccountAuthenticatorActivity.onDestroy,android.preference.PreferenceActivity.onDestroy,android.support.v4.app.FragmentActivity.onDestroy,android.app.TabActivity.onDestroy,android.support.v7.app.ActionBarActivity.onDestroy,android.app.ActivityGroup.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onDestroy()) |- [CB] [ENTRY] [a] void android.app.Activity.onRestart() ALIASES android.app.Activity.onRestart = [android.app.LauncherActivity.onRestart,android.support.v7.app.AppCompatActivity.onRestart,android.app.ExpandableListActivity.onRestart,android.app.ListActivity.onRestart,android.app.AliasActivity.onRestart,android.accounts.AccountAuthenticatorActivity.onRestart,android.preference.PreferenceActivity.onRestart,android.support.v4.app.FragmentActivity.onRestart,android.app.TabActivity.onRestart,android.support.v7.app.ActionBarActivity.onRestart,android.app.ActivityGroup.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart,android.app.Activity.onRestart],android.app.Activity.onDestroy = [android.app.LauncherActivity.onDestroy,android.support.v7.app.AppCompatActivity.onDestroy,android.app.ExpandableListActivity.onDestroy,android.app.ListActivity.onDestroy,android.app.AliasActivity.onDestroy,android.accounts.AccountAuthenticatorActivity.onDestroy,android.preference.PreferenceActivity.onDestroy,android.support.v4.app.FragmentActivity.onDestroy,android.app.TabActivity.onDestroy,android.support.v7.app.ActionBarActivity.onDestroy,android.app.ActivityGroup.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onDestroy()) |- [CB] [ENTRY] [a] void android.app.Activity.onDestroy() ALIASES android.app.Activity.onDestroy = [android.app.LauncherActivity.onDestroy,android.support.v7.app.AppCompatActivity.onDestroy,android.app.ExpandableListActivity.onDestroy,android.app.ListActivity.onDestroy,android.app.AliasActivity.onDestroy,android.accounts.AccountAuthenticatorActivity.onDestroy,android.preference.PreferenceActivity.onDestroy,android.support.v4.app.FragmentActivity.onDestroy,android.app.TabActivity.onDestroy,android.support.v7.app.ActionBarActivity.onDestroy,android.app.ActivityGroup.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy];
SPEC (((TRUE)[*]); [CB] [ENTRY] [a] void android.app.Activity.onDestroy()) |- [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) ALIASES android.app.Activity.onDestroy = [android.app.LauncherActivity.onDestroy,android.support.v7.app.AppCompatActivity.onDestroy,android.app.ExpandableListActivity.onDestroy,android.app.ListActivity.onDestroy,android.app.AliasActivity.onDestroy,android.accounts.AccountAuthenticatorActivity.onDestroy,android.preference.PreferenceActivity.onDestroy,android.support.v4.app.FragmentActivity.onDestroy,android.app.TabActivity.onDestroy,android.support.v7.app.ActionBarActivity.onDestroy,android.app.ActivityGroup.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy,android.app.Activity.onDestroy],android.app.Activity.onCreate = [android.app.LauncherActivity.onCreate,android.support.v7.app.AppCompatActivity.onCreate,android.app.ExpandableListActivity.onCreate,android.app.ListActivity.onCreate,android.app.AliasActivity.onCreate,android.accounts.AccountAuthenticatorActivity.onCreate,android.preference.PreferenceActivity.onCreate,android.support.v4.app.FragmentActivity.onCreate,android.app.TabActivity.onCreate,android.support.v7.app.ActionBarActivity.onCreate,android.app.ActivityGroup.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate,android.app.Activity.onCreate]


//disable start when coming from create/start

//SPEC TRUE[*]; [CB] [ENTRY] [a] void android.app.Activity.onStop() |- [CB] [ENTRY] [a] void android.app.Activity.onStart();



//disable create when coming from create/start

//SPEC TRUE[*]; [CB] [ENTRY] [a] void android.app.Activity.onStop() |- [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle);





//TODO: this branch of the lifecycle appears to necessitate destroying the process meaning the activity will be recreated

////Create branch from stop

//SPEC TRUE[*]; [CB] [ENTRY] [a] void android.app.Activity.onStop() |+ [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle);

//SPEC TRUE[*]; [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) |- [CB] [ENTRY] [a] void android.app.Activity.onRestart();

//SPEC TRUE[*]; [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle) |- [CB] [ENTRY] [a] void android.app.Activity.onDestroy()

//SPEC TRUE[*]; [CB] [ENTRY] [a] void android.app.Activity.onStop() |+ [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle);

//SPEC TRUE[*]; [CB] [ENTRY] [a] void android.app.Activity.onStop() |- [CB] [ENTRY] [a] void android.app.Activity.onCreate(# : android.os.Bundle);





