//Auto generated by fragment-alias-gen.py do not edit
REGEXP Fragment_all_onStart(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onStart()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onStart()
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onStart()
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onStart()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onStart()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onStart()
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onStart()
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onStart()
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onStart()
)];
REGEXP Fragment_all_onResume(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onResume()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onResume()
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onResume()
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onResume()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onResume()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onResume()
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onResume()
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onResume()
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onResume()
)];
REGEXP Fragment_all_onPause(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onPause()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onPause()
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onPause()
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onPause()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onPause()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onPause()
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onPause()
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onPause()
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onPause()
)];
REGEXP Fragment_all_onSaveInstanceState(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onSaveInstanceState(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onSaveInstanceState(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onSaveInstanceState(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onSaveInstanceState(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onSaveInstanceState(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onSaveInstanceState(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onSaveInstanceState(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onSaveInstanceState(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onSaveInstanceState(# : android.os.Bundle)
)];
REGEXP Fragment_all_onDestroy(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onDestroy()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onDestroy()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onDestroy()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onDestroy()
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onDestroy()
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onDestroy()
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onDestroy()
)];
REGEXP Fragment_all_onDetach(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onDetach()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onDetach()
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onDetach()
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onDetach()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onDetach()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onDetach()
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onDetach()
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onDetach()
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onDetach()
)];
REGEXP Fragment_all_onCreateView(f) = [(
    [CB] [ENTRY] [f] android.view.View android.support.v4.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] android.view.View android.support.v4.app.ListFragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] android.view.View android.app.ListFragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] android.view.View android.app.Fragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] android.view.View android.support.v4.app.DialogFragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] android.view.View android.preference.PreferenceFragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] android.view.View android.app.DialogFragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] android.view.View android.webkit.WebViewFragment.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] android.view.View android.support.v7.preference.PreferenceFragmentCompat.onCreateView(# : android.view.LayoutInflater,# : android.view.ViewGroup,# : android.os.Bundle)
)];
REGEXP Fragment_all_onViewCreated(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onViewCreated(# : android.view.View,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onViewCreated(# : android.view.View,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onViewCreated(# : android.view.View,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onViewCreated(# : android.view.View,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onViewCreated(# : android.view.View,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onViewCreated(# : android.view.View,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onViewCreated(# : android.view.View,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onViewCreated(# : android.view.View,# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onViewCreated(# : android.view.View,# : android.os.Bundle)
)];
REGEXP Fragment_all_onDestroyView(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onDestroyView()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onDestroyView()
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onDestroyView()
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onDestroyView()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onDestroyView()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onDestroyView()
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onDestroyView()
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onDestroyView()
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onDestroyView()
)];
REGEXP Fragment_all_init(f) = [(
    [CI] [ENTRY] [f] void android.support.v4.app.Fragment.<init>()
    |
    [CI] [ENTRY] [f] void android.support.v4.app.ListFragment.<init>()
    |
    [CI] [ENTRY] [f] void android.app.ListFragment.<init>()
    |
    [CI] [ENTRY] [f] void android.app.Fragment.<init>()
    |
    [CI] [ENTRY] [f] void android.support.v4.app.DialogFragment.<init>()
    |
    [CI] [ENTRY] [f] void android.preference.PreferenceFragment.<init>()
    |
    [CI] [ENTRY] [f] void android.app.DialogFragment.<init>()
    |
    [CI] [ENTRY] [f] void android.webkit.WebViewFragment.<init>()
    |
    [CI] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.<init>()
)];
REGEXP Fragment_all_onStop(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onStop()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onStop()
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onStop()
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onStop()
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onStop()
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onStop()
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onStop()
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onStop()
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onStop()
)];
REGEXP Fragment_all_onCreate(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onCreate(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onCreate(# : android.os.Bundle)
)];
REGEXP Fragment_all_onAttach(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onAttach(# : android.app.Activity)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onAttach(# : android.app.Activity)
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onAttach(# : android.app.Activity)
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onAttach(# : android.app.Activity)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onAttach(# : android.app.Activity)
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onAttach(# : android.app.Activity)
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onAttach(# : android.app.Activity)
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onAttach(# : android.app.Activity)
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onAttach(# : android.app.Activity)
)];
REGEXP Fragment_all_onActivityCreated(f) = [(
    [CB] [ENTRY] [f] void android.support.v4.app.Fragment.onActivityCreated(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.ListFragment.onActivityCreated(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.ListFragment.onActivityCreated(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.Fragment.onActivityCreated(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v4.app.DialogFragment.onActivityCreated(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.preference.PreferenceFragment.onActivityCreated(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.app.DialogFragment.onActivityCreated(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.webkit.WebViewFragment.onActivityCreated(# : android.os.Bundle)
    |
    [CB] [ENTRY] [f] void android.support.v7.preference.PreferenceFragmentCompat.onActivityCreated(# : android.os.Bundle)
)];
REGEXP Fragment_all_isDetached(f) = [(
    [CI] [ENTRY] [f] boolean android.support.v4.app.Fragment.isDetached()
    |
    [CI] [ENTRY] [f] boolean android.support.v4.app.ListFragment.isDetached()
    |
    [CI] [ENTRY] [f] boolean android.app.ListFragment.isDetached()
    |
    [CI] [ENTRY] [f] boolean android.app.Fragment.isDetached()
    |
    [CI] [ENTRY] [f] boolean android.support.v4.app.DialogFragment.isDetached()
    |
    [CI] [ENTRY] [f] boolean android.preference.PreferenceFragment.isDetached()
    |
    [CI] [ENTRY] [f] boolean android.app.DialogFragment.isDetached()
    |
    [CI] [ENTRY] [f] boolean android.webkit.WebViewFragment.isDetached()
    |
    [CI] [ENTRY] [f] boolean android.support.v7.preference.PreferenceFragmentCompat.isDetached()
)];
REGEXP Fragment_all_isResumed(f) = [(
    [CI] [ENTRY] [f] boolean android.support.v4.app.Fragment.isResumed()
    |
    [CI] [ENTRY] [f] boolean android.support.v4.app.ListFragment.isResumed()
    |
    [CI] [ENTRY] [f] boolean android.app.ListFragment.isResumed()
    |
    [CI] [ENTRY] [f] boolean android.app.Fragment.isResumed()
    |
    [CI] [ENTRY] [f] boolean android.support.v4.app.DialogFragment.isResumed()
    |
    [CI] [ENTRY] [f] boolean android.preference.PreferenceFragment.isResumed()
    |
    [CI] [ENTRY] [f] boolean android.app.DialogFragment.isResumed()
    |
    [CI] [ENTRY] [f] boolean android.webkit.WebViewFragment.isResumed()
    |
    [CI] [ENTRY] [f] boolean android.support.v7.preference.PreferenceFragmentCompat.isResumed()
)]
